### ISSUE TITLE
hilo error when sampling distribution has missing values

### ISSUE THREAD

**Issue by robjhyndman** [mitchelloharawild/distributional#13]
``` r
library(distributional)
library(magrittr)
dist_sample(list(c(NA,rnorm(20)))) %>% hilo()
#> Error in quantile.default(X[[i]], ...): missing values and NaN's not allowed if 'na.rm' is FALSE
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think it would be reasonable to generate a warning here rather than an error, and pass `na.rm=TRUE` to `quantile()`.

**Comment by mitchelloharawild** [comment]
Is there any value to having NA values in `dist_sample()`? Perhaps the warning should occur on object creation.

**Comment by robjhyndman** [comment]
Yes, that would be an alternative (or warn in both functions). There is no value in having NAs, but sometimes they might be generated. For example, if the distribution is a set of percentiles, then it is possible that some NAs will be generated due to the percentiles not covering the full range (0,100).

**Comment by mitchelloharawild** [comment]
Fixed, thanks.
