### ISSUE TITLE
fable and distributional packages: hilo() function error

### ISSUE THREAD

**Issue by amarjitsinghchandhial** [mitchelloharawild/distributional#130]
Hi,

There's an issue with the hilo() function, I posted on the Posit Community Forum with a  minimal reproducible example: https://forum.posit.co/t/fable-and-distributional-packages-hilo-function-error/193716.

Please can you resolve.

thanks,
Amarjit

**Comment by mitchelloharawild** [comment]
Thanks for letting me know. This is being discussed in #129.

**Comment by mitchelloharawild** [comment]
This should now be fixed, you can find more details in #129

**Comment by amarjitsinghchandhial** [comment]
Thanks Mitch.
