### ISSUE TITLE
Simulated distributions with known mean

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/distributional#17]
cc @robjhyndman

Some forecast methods such as `forecast.ETS()` use the analytical forecast mean for the point forecast, and the simulated paths for the uncertainty. Should we create a new distribution modifier for distributions with known mean, or change the forecast behaviour to use sample means for point forecasts?

**Comment by robjhyndman** [comment]
The analytical means are probably a little more accurate, but I'm in favour of simplicity. And since you have to do the simulation anyway, I think we could just use the sample means.

**Comment by mitchelloharawild** [comment]
Great, thanks!
