### ISSUE TITLE
Scaled-and-shifted Student's t distribution?

### ISSUE THREAD

**Issue by mjskay** [mitchelloharawild/distributional#28]
From an uncertainty vis perspective, having a scaled-and-shifted Student's t dist would be *very* useful: it's pretty common for both frequentist confidence distributions and Bayesian priors. 

As a bonus, if it followed the Stan parameter order (df, location, scale) it would even more useful :).

My humble suggestion would be to modify dist_student_t to use something like (df, mu, sigma, ncp) (assuming not too many people have starting using it yet / or tend to use ncp as a named parameter anyway).

**Comment by mjskay** [comment]
I'm happy to write a PR for this if you want it. I would propose changing the signature of `dist_student_t` from `dist_student_t(df, ncp = NULL)` to `dist_student_t(df, mu = 0, sigma = 1, ncp = NULL)` and updating the other functions for the student t distribution accordingly.

**Comment by mitchelloharawild** [comment]
A PR would be great for this. Thanks!
