### ISSUE TITLE
Recommended doc page to link to for distribution objects?

### ISSUE THREAD

**Issue by mjskay** [mitchelloharawild/distributional#31]
As I'm writing docs in ggdist about support for distributional, I find myself looking for a central help page on distribution objects --- something the docs for the `dist` aesthetic can point to as a good jumping-off point for readers to learn about them. Is there such a page? I wasn't able to find one but I might have missed it. If there isn't, it could be helpful to have :). Thanks!

**Comment by mitchelloharawild** [comment]
Best consolidated resource for this is the pkgdown reference at the moment.
A vignette and/or auto-generated distribution listing would be useful for this.

**Comment by mjskay** [comment]
Thanks! I'll point to the pkgdown for now

**Comment by mitchelloharawild** [comment]
I think long term the pkgdown documentation is the best link, and as needed I'll extend the README with links to the most important learning resources (vignettes, lists of distributions, etc).
