### ISSUE TITLE
Support auto-linking across pkgdown sites

### ISSUE THREAD

**Issue by mjskay** [mitchelloharawild/distributional#32]
If you add this to the top of `_pkgdown.yml`:

```yml
url: http://pkg.mitchelloharawild.com/distributional
```

pkgdown sites of other packages (like ggdist :)) will automatically link references to distributional functions in their documentation to your pkgdown site (see https://pkgdown.r-lib.org/reference/build_site.html#yaml-config)

**Comment by mitchelloharawild** [comment]
Thanks!
