### ISSUE TITLE
Remove graphics utilities in favour of `{ggdist}`

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/distributional#62]
The dependency is not needed thanks to the wonderful work by @mjskay at https://github.com/mjskay/ggdist/.
The usage in {fabletools} will be updated to use (and suggest) the {ggdist} package, reducing the dependency tree for all associated packages.

I don't expect that many people use `geom_hilo_ribbon()` or `geom_hilo_linerange()` yet, so the deprecation can happen fairly quickly (perhaps 1 major release).

**Comment by mitchelloharawild** [comment]
Waiting for https://github.com/mjskay/ggdist/issues/111 to allow `{fabletools}` to use `{ggdist}` before `{distributional}` can drop `geom_*()` functions.

**Comment by dmi3kno** [comment]
Trimming down heavy dependencies, e.g. {ggplot2} is very much appreciated!
