### ISSUE TITLE
Suggest change in argument names in `dist_student_t` and `dist_normal`

### ISSUE THREAD

**Issue by emitanaka** [mitchelloharawild/distributional#76]
I reckon you should have the argument names as `mean` and `sd` and deprecate `mu` and `sigma` for `dist_normal` and `dist_student_t`. This is consistent with how you do other distributions, e.g. "shape" and "rate" in gamma distribution + how the `stats::dnorm` works too.

**Comment by emitanaka** [comment]
I can update the arguments + deprecation notice in a pull request if you want

**Comment by mitchelloharawild** [comment]
What do you think about aliasing the arguments, so that either `mu` or `mean` and `sigma` or `sd` can be used?

**Comment by mjskay** [comment]
Possible nitpick: for student t, sigma is not the standard deviation unless df = Inf, no? Perhaps a more "semantic" alias for sigma in student t would be "scale"?

**Comment by mitchelloharawild** [comment]
I think that's reason enough to not have `mean` and `sd` for student t distributions. The motivation for 'how stats does it' doesn't apply for this distribution anyway.
