### ISSUE TITLE
Getting levels of categorical distributions and samples

### ISSUE THREAD

**Issue by mjskay** [mitchelloharawild/distributional#89]
Is there / should there be a way to get the levels in the support of a categorical distribution (or in a sample from one?).

Currently `support()` does not list the levels:

```r
x = dist_categorical(list(1:5), list(letters[1:5]))
unclass(support(x))
#> $x
#> $x[[1]]
#> character(0)
#> 
#> 
#> $lim
#> $lim[[1]]
#> [1] NA
```

It would be nice to be able to get the list of unique values in the support, maybe here (perhaps in `$lim`)? That would be consistent with how ggplot uses "limits" on discrete versus continuous scales, for example. I could also see something like a "levels" field.

Relatedly, if we create a `dist_sample()` on a character, factor, or ordered vector, `support()` fails:

```r
support(dist_sample(list(letters[1:5])))
#> Error in (1 - h) * qs[i]: non-numeric argument to binary operator
support(dist_sample(list(factor(letters[1:5]))))
#> Error in quantile.default(x$x, probs = p, ..., na.rm = na.rm, names = FALSE): (unordered) factors are not allowed
support(dist_sample(list(ordered(letters[1:5]))))
#> Error in quantile.default(x$x, probs = p, ..., na.rm = na.rm, names = FALSE): 'type' must be 1 or 3 for ordered factors
```

Happy to submit a PR implementing the desired solution.

**Comment by mitchelloharawild** [comment]
Thanks! Not sure what the best interface would be for this, but `support()` would be a sensible place for it. I can do the implementation of this one.

**Comment by mjskay** [comment]
Thanks!

**Comment by mjskay** [comment]
awesome thanks!
