### ISSUE TITLE
Reverse dependency check failure

### ISSUE THREAD

**Issue by teunbrand** [mitchelloharawild/distributional#93]
Hi Mitchell,

We have been preparing a new release of ggplot2 and during a reverse dependency check, it became apparent that the prospective ggplot2 3.5.0 would break distributional.

Now I noticed some activity, e.g. https://github.com/mitchelloharawild/distributional/commit/4d6eb3f2dbf2b2c8dc3aa3e1aba92b78cb4bdf02 that would suggest that this becomes a non-issue some time in the future. As ggplot2 aims to release 3.5.0 on the 12th of February, I'm mostly inquiring about whether distributional plans on detaching from ggplot2 before or after that date (if my assumption to detach is correct). If the answer is 'after', then I'm more than happy to put in a PR for a (temporary) fix. If the answer is 'before', then I guess this doesn't really matter.

Would you please let me know what your plans are and if I can be of any help making distributional compatible with ggplot2 3.5.0?

To test the code changes with the release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588.

**Comment by teunbrand** [comment]
This is just a kind reminder that the release is scheduled soon. If you'd like any help, please let me know.

**Comment by mitchelloharawild** [comment]
The package has been updated on CRAN and should now be compatible with ggplot2 3.5.0.
