### ISSUE TITLE
distributional 0.4.0

### ISSUE THREAD

**Issue by amarjitsinghchandhial** [mitchelloharawild/distributional#94]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
Hi Mitch,

I have just updated to distibutional 0.4.0 and get the following error when trying to load library fpp3:

library(fpp3)
Error: package or namespace load failed for ‘fpp3’:
object ‘guide_level’ is not exported by 'namespace:distributional'

Please advise.

cheers,
Amarjit
```r
# insert reprex here
```

**Comment by mitchelloharawild** [comment]
You will need to update the fabletools package to produce forecasts with the latest version of distributional.
